//Crashday Widescreen Fix by St1ngLeR//

[General]
; This overrides game's aspect ratio
; Examples: auto, 4:3, 5:4, 16:9, *:*
ForceAspectRatio=auto

; This fixes the scaling of texture-based HUD messages
FixHUDMessagesScale=1

; Scale multiplier for the HUD messages (if "FixHUDMessagesScale" is enabled)
HUDMessagesScale=1.1

; This fixes the scaling of light flares (i.e. emitting from cars)
FixLightFlaresScale=1

; Scale multiplier for the lgiht flares (if "FixLightFlaresScale" is enabled)
LightFlaresScale=1.1